AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Infrastructure template

Parameters:
  StageName:
    Type: String
  AppName:
    Type: String
  TableName:
    Type: String
    Description: Name of the DynamoDB table
  AppApiId:
    Type: String
    Description: The ID of the AppApi from the parent stack

Resources:
  DynamoDBStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./dynamodb.yaml
      Parameters:
        TableName: !Ref TableName

  CognitoStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./cognito.yaml
      Parameters:
        StageName: !Ref StageName
        AppName: !Ref AppName
        AppApiId: !Ref AppApiId

Outputs:
  CognitoAdminGroupArn:
    Description: "ARN of the Admin user pool group from Cognito stack"
    Value: !GetAtt CognitoStack.Outputs.AdminGroupArn
  CognitoUserPoolArn:
    Value: !GetAtt CognitoStack.Outputs.UserPoolArn
  CognitoUserPoolId:
    Value: !GetAtt CognitoStack.Outputs.UserPoolId
