version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::014183400304:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-9ZMN5M5UHRIM"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::014183400304:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1AKAHBSYJ48NB"
cloudformation_execution_role = "arn:aws:iam::014183400304:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-MF7NCGMV4R84"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-15zzrtj4uvppu"
image_repository = ""
region = "ap-southeast-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::014183400304:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-1C9WXLP1ZHOTZ"
cloudformation_execution_role = "arn:aws:iam::014183400304:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-1M6SWR0G0HB69"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1vz63wibsar8h"
image_repository = ""
region = "ap-southeast-1"
